version: 0.0
 os: linux
 files:
   - source: /
     destination: /home/ubuntu
     overwrite: yes
 permission:
   - object: /home/ubuntu
     pattern: "**"
     owner: ec2-user
     group: ec2-user
 hooks:
   ApplicationStop:
     - location: kill_process.sh
       timeout: 100
       runas: root
   ApplicationStart:
     - location: run_process.sh
       timeout: 3600
       runas: root